"""Add PricingRule and Payments table

Revision ID: 0499fcc6fd1d
Revises: 5b66a18bd77b
Create Date: 2025-05-04 22:53:37.133504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0499fcc6fd1d'
down_revision: Union[str, None] = '5b66a18bd77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricingrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column(
        'category',
        postgresql.ENUM(
            'economy', 'standard', 'premium',
            name='vehiclecategory',
            create_type=False,
            native_enum=False
        ),
        nullable=False
    ),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('price_per_km_day', sa.Float(), nullable=False),
    sa.Column('price_per_km_night', sa.Float(), nullable=False),
    sa.Column('airport_surcharge', sa.Float(), nullable=False),
    sa.Column('holiday_surcharge', sa.Float(), nullable=False),
    sa.Column('passenger_surcharge', sa.Float(), nullable=False),
    sa.Column('min_fare', sa.Float(), nullable=False),
    sa.Column('min_fare_airport', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('card', 'cash', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', 'canceled', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('booking', 'payment_method')
    op.drop_column('booking', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('payment')
    op.drop_table('pricingrule')
    # ### end Alembic commands ###
