"""Addded is_company_owned variable to vehicle

Revision ID: 696c5c2c157c
Revises: bb2782de6889
Create Date: 2025-05-03 18:41:37.422155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696c5c2c157c'
down_revision: Union[str, None] = 'bb2782de6889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('is_company_owned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'is_company_owned')
    # ### end Alembic commands ###
