"""Add expired and payment_failed status enums

Revision ID: ea424ae2a879
Revises: 0499fcc6fd1d
Create Date: 2025-06-01 04:05:09.252458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea424ae2a879'
down_revision: Union[str, None] = '0499fcc6fd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add missing enum values manually
    op.execute("ALTER TYPE bookingstatus ADD VALUE 'confirmed'")
    op.execute("ALTER TYPE bookingstatus ADD VALUE 'expired'")
    op.execute("ALTER TYPE bookingstatus ADD VALUE 'payment_failed'")
    op.execute("ALTER TYPE paymentstatus ADD VALUE 'expired'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
